/*
 * Patrick Angle Commons Library
 * Copyright 2018 Patrick Angle
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *    http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.patrickangle.commons.swing;

import com.patrickangle.commons.logging.Logging;
import com.patrickangle.commons.util.AquaUtils;
import com.patrickangle.commons.util.Colors;
import java.awt.SystemColor;
import java.lang.reflect.InvocationTargetException;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.plaf.ColorUIResource;
import javax.swing.plaf.PanelUI;
import javax.swing.plaf.RootPaneUI;

/**
 *
 * @author patrickangle
 */
public class Tester extends javax.swing.JFrame {

    /**
     * Creates new form Tester
     */
    public Tester() {
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setTitle("Testing Dialog");
        this.getRootPane().putClientProperty(AquaUtils.WINDOW_STYLE, AquaUtils.WINDOW_STYLE_VALUE_HUD);
        this.getRootPane().putClientProperty(AquaUtils.WINDOW_BRUSH_METAL_LOOK, Boolean.TRUE);
        this.getRootPane().putClientProperty(AquaUtils.WINDOW_TRANSPARENT_TITLE_BAR, Boolean.TRUE);

        try {
            Class aquaPanelUiClass = this.getClass().getClassLoader().loadClass("com.apple.laf.AquaPanelUI");
            if (this.getContentPane() instanceof JPanel) {
                ((JPanel) this.getContentPane()).setUI((PanelUI) aquaPanelUiClass.getConstructor().newInstance());
            }
        } catch (ClassNotFoundException | NoSuchMethodException | SecurityException | InstantiationException | IllegalAccessException | IllegalArgumentException | InvocationTargetException ex) {
            Logging.exception(this, ex);
        }
        
        this.getContentPane().setBackground(new ColorUIResource(SystemColor.window));
        
        initComponents();
        
        System.out.println(SystemColor.textHighlight.getRed());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setType(java.awt.Window.Type.UTILITY);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(125, 125, 125))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new TesterDialog(this, true).setVisible(true);
        this.getRootPane().putClientProperty(AquaUtils.WINDOW_TRANSPARENT_TITLE_BAR, Boolean.FALSE);
        this.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tester().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
